web/router.ex
defmodule Timesheet.Router do
  use Timesheet.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Timesheet.Plugs.UserStatus
    plug Timesheet.Plugs.Timezone
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Timesheet do
    pipe_through :browser # Use the default browser stack

    get "/", EntryController, :index
    resources "/entries", EntryController
    get "/overview", OverviewController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", Timesheet do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Timesheet.LayoutView do
  use Timesheet.Web, :view

  def inverse("OUT"), do: "IN"
  def inverse("IN"), do: "OUT"

  def active?(%Plug.Conn{private: %{phoenix_view: view}}, page) do
    view.active?(page)
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Timesheet</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <script id="page-data" type="application/json">
      <%= page_data(@conn) %>
    </script>
  </head>

  <body>
    <div class="container" role="main">
      <div class="row">
        <div class="col-md-2 col-md-push-10">
          <div class="panel panel-default">
            <div class="panel-heading">
              You are <%= @user_status %>
            </div>
            <div class="panel-body">
              <%= form_for @conn, entry_path(@conn, :create), [as: :entry], fn f -> %>
                <%= hidden_input(f, :type, value: inverse(@user_status)) %>
                <%= submit("GO #{inverse(@user_status)}", class: "btn btn-primary") %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-md-10 col-md-pull-2">
          <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

          <ul class="nav nav-tabs">
            <li class="<%= active?(@conn, :overview) %>"><a href="<%= overview_path(@conn, :index) %>">Overzicht</a></li>
            <li class="<%= active?(@conn, :entries) %>"><a href="<%= entry_path(@conn, :index) %>">Boekingen</a></li>
          </ul>
          <%= render @view_module, @view_template, assigns %>
        </div>
      </div>
    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>